### ISSUE TITLE
Release v1.110: Assertion `!node.ports.empty()' failed

### ISSUE THREAD

**Issue by Gordon-Dry** [lolluslollus/lollo_freestyle_train_station_1#10]
With release version 1.110 on Tpf2 beta build 35210, heavily modded.

After I created the first two platforms (top on savegame screenshot from before I started);
![Region Goslar 02d](https://user-images.githubusercontent.com/29145213/221706179-de04f1be-44ed-4224-894d-52bd3ab11700.jpg)
I wanted to add a seperated 3rd platform, see this screenshot
![autosave_Region Goslar 01w_1801-04-23](https://user-images.githubusercontent.com/29145213/221706600-9d022d0c-7ab3-4380-a74a-125d3e30d3a2.jpg)
That 3rd platform is near to the edge of the industry, but not too tight (about 1m away), no road inbetween.

After about 30 seconds the game crashed.
Did the mod try to draw lanes through the industry or the stub end of the sand road?

End of log:
```
_getNodeBetween starting, shift0To1 =	0.84871426681064	length =	72.00020249674
pos0, pos1 =
{
  x = 2888.8864746094,
  y = -7657.6801757813,
  z = 8.2320327758789,
}
{
  x = 2900.1496582031,
  y = -7586.5668945313,
  z = 8.2320327758789,
}
tan0, tan1 =
{
  x = 11.263248443604,
  y = 71.113761901855,
  z = -0,
}
{
  x = 11.263312339783,
  y = 71.11376953125,
  z = -0,
}
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/A9F18CB9FBA33F747B71F05AEC5E4C3A/totally_transparent_albedo.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/A9F18CB9FBA33F747B71F05AEC5E4C3A/totally_transparent_metal_gloss_ao.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/A9F18CB9FBA33F747B71F05AEC5E4C3A/totally_transparent_albedo.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/A9F18CB9FBA33F747B71F05AEC5E4C3A/totally_transparent_metal_gloss_ao.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/7B8D22109DDB4B703192D966A1DD2686/big_03.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/7B8D22109DDB4B703192D966A1DD2686/small_05.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/DE7E18F3023041836D86395F6D672C8D/ETH_transparent.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/7B8D22109DDB4B703192D966A1DD2686/big_03.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/7B8D22109DDB4B703192D966A1DD2686/small_05.compressed.mm.dds not in file cache!
_getNodeBetween starting, shift0To1 =	0.84908566964568	length =	72.00020249674
pos0, pos1 =
{
  x = 2883.9479980469,
  y = -7656.8979492188,
  z = 8.2320327758789,
}
{
  x = 2895.2111816406,
  y = -7585.7846679688,
  z = 8.2320327758789,
}
tan0, tan1 =
{
  x = 11.263248443604,
  y = 71.113761901855,
  z = -0,
}
{
  x = 11.263312339783,
  y = 71.11376953125,
  z = -0,
}
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/7B8D22109DDB4B703192D966A1DD2686/big_03.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/7B8D22109DDB4B703192D966A1DD2686/small_05.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/DE7E18F3023041836D86395F6D672C8D/ETH_transparent.compressed.mm.dds not in file cache!
urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:392: void __cdecl ecs::TransportNetworkSystem::EntityAdded(class ecs::Engine *,const class ecs::Entity &): Assertion `edge.conns[0] != edge.conns[1]' failed.
urban_games/train_fever/src/Lib/renderer/TransportNetworkRenderer.cpp:274: void __cdecl TransportNetworkRenderer::Add(class ecs::Entity,const struct ecs::component::TransportNetwork &): Assertion `!node.ports.empty()' failed.
urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:392: void __cdecl ecs::TransportNetworkSystem::EntityAdded(class ecs::Engine *,const class ecs::Entity &): Assertion `edge.conns[0] != edge.conns[1]' failed.
Attempting to write crash save to "crash_Region Goslar 01w_2023-02-27_23-49-58"
available disk space: 5139 MB
[2023-02-27 23:49:58] Saving to file C:/Users/Admin/AppData/Roaming/Transport Fever 2/save/crash_Region Goslar 01w_2023-02-27_23-49-58.sav
Saving...: 17247.1 ms
Additional info extracted from the previous state:
Uncaught exception while in class UI::CSelector
Exception type: Fatal error

Details:

Assertion Failure: Assertion `!node.ports.empty()' failed.

Minidump: C:/Users/Admin/AppData/Roaming/Transport Fever 2/crash_dump/154cfdf1-138b-4a38-b580-d099d4f2b904.dmp

In file: urban_games/train_fever/src/Lib/renderer/TransportNetworkRenderer.cpp:274

In function: void __cdecl TransportNetworkRenderer::Add(class ecs::Entity,const struct ecs::component::TransportNetwork &)


__CRASHDB_CRASH__ struct AssertException: urban_games/train_fever/src/Lib/renderer/TransportNetworkRenderer.cpp:274: void __cdecl TransportNetworkRenderer::Add(class ecs::Entity,const struct ecs::component::TransportNetwork &): Assertion `!node.ports.empty()' failed.
Exception type: Fatal error

Details:

Assertion Failure: Assertion `!node.ports.empty()' failed.

Minidump: C:/Users/Admin/AppData/Roaming/Transport Fever 2/crash_dump/154cfdf1-138b-4a38-b580-d099d4f2b904.dmp

In file: urban_games/train_fever/src/Lib/renderer/TransportNetworkRenderer.cpp:274

In function: void __cdecl TransportNetworkRenderer::Add(class ecs::Entity,const struct ecs::component::TransportNetwork &)



Goodbye.



========================================
Shutdown at Mon Feb 27 23:50:37 2023
========================================
```

Log (two crash dumps in a row):
[crash_dump.zip](https://github.com/lolluslollus/lollo_freestyle_train_station_1/files/10844966/crash_dump.zip)

**Comment by Gordon-Dry** [comment]
New test after I fixed the other issue:
https://github.com/lolluslollus/lollo_freestyle_train_station_1/issues/8

Finished the main part of the cargo station:
![Region Goslar 02g2 TEST](https://user-images.githubusercontent.com/29145213/221911762-6aaeefdf-1ff7-4d19-b08a-b604d5e7d8e8.jpg)

Now I want to add this part:
![20230228_171326_img-0](https://user-images.githubusercontent.com/29145213/221912015-f28ad403-c7ad-4ab2-a506-1862094bf799.jpg)

Yes! It worked:
![Screen-2023-02-28_17-17-26](https://user-images.githubusercontent.com/29145213/221913143-bbb7185d-46d5-4f50-a109-773af614e2ba.jpg)

The difference:
There is a road between the edge of the industry and the platform, plus the gap for extensions.

I close this issue for now.

**Comment by Gordon-Dry** [comment]
It happened again with v1.117.

A straight station, no bends, no external platforms, but ... not far away from the short edge of an 1:5 megalomaniac map.
Afaik the precision of game pointers decreases the further away an object is from the center of the map, expecially on the bigger maps.
Side note: this also is the reason for increased z-fighting aka. texture flickering near to the map edges, no matter if static objects or moving models.

I assume that this triggers the crash.
[crash_dump.zip](https://github.com/lolluslollus/lollo_freestyle_train_station_1/files/10951261/crash_dump.zip)

**Comment by Gordon-Dry** [comment]
This time near the long edge of the 1:5 megalomaniac map, another variant of the crash.

It looked  like if the platform will be created, but then freeze and this crash (end of log):
```
urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:392: void __cdecl ecs::TransportNetworkSystem::EntityAdded(class ecs::Engine *,const class ecs::Entity &): Assertion `edge.conns[0] != edge.conns[1]' failed.
Attempting to write crash save to "crash_Region Goslar 08t_2023-03-12_21-47-56"
available disk space: 9639 MB
[2023-03-12 21:47:56] Saving to file C:/Users/Admin/AppData/Roaming/Transport Fever 2/save/crash_Region Goslar 08t_2023-03-12_21-47-56.sav
Saving...: 15235.3 ms
creating post-mortem savegame failed
Additional info extracted from the previous state:
 Additional info for entity 163060: 
 revision: 45 / 5 / 0
  components: 
   struct ecs::component::Name
   struct ecs::component::PlayerOwned
   struct ecs::component::BoundingVolume
   struct ecs::component::ModelInstanceList
   struct ecs::component::TransportNetwork

nil

GC Called
Destroying failback ui done
Uncaught exception while in class UI::CSelector
Exception type: Fatal error

Details:

Assertion Failure: Assertion `edge.conns[0] != edge.conns[1]' failed.

Minidump: C:/Users/Admin/AppData/Roaming/Transport Fever 2/crash_dump/290e748c-9d53-4f10-9905-cac6b3488f4b.dmp

Entity: 163060

Notified Entity: 163060

UI Component Hierarchy: 
 type: class UI::CGameUI, id = "", name = "CGameUI", styleClasses = {"top-gamebar-visible"}
 type: class UI::CMenuUI, id = "", name = "MenuUI", styleClasses = {}
 type: class UI::CComponent, id = "", name = "wrap", styleClasses = {"platform-desktop", "ui-classic", "input-mouse", "gamepad-type-xbox"}


In file: urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:392

In function: void __cdecl ecs::TransportNetworkSystem::EntityAdded(class ecs::Engine *,const class ecs::Entity &)


__CRASHDB_CRASH__ struct AssertException: urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:392: void __cdecl ecs::TransportNetworkSystem::EntityAdded(class ecs::Engine *,const class ecs::Entity &): Assertion `edge.conns[0] != edge.conns[1]' failed.
Exception type: Fatal error

Details:

Assertion Failure: Assertion `edge.conns[0] != edge.conns[1]' failed.

Minidump: C:/Users/Admin/AppData/Roaming/Transport Fever 2/crash_dump/290e748c-9d53-4f10-9905-cac6b3488f4b.dmp

Entity: 163060

Notified Entity: 163060

UI Component Hierarchy: 
 type: class UI::CGameUI, id = "", name = "CGameUI", styleClasses = {"top-gamebar-visible"}
 type: class UI::CMenuUI, id = "", name = "MenuUI", styleClasses = {}
 type: class UI::CComponent, id = "", name = "wrap", styleClasses = {"platform-desktop", "ui-classic", "input-mouse", "gamepad-type-xbox"}


In file: urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:392

In function: void __cdecl ecs::TransportNetworkSystem::EntityAdded(class ecs::Engine *,const class ecs::Entity &)
```
[crash_dump.zip](https://github.com/lolluslollus/lollo_freestyle_train_station_1/files/10952067/crash_dump.zip)

**Comment by Gordon-Dry** [comment]
This time, with the latest repo, trying the same station as before (I saved after I laid the tracks), just one line in the stdout.txt before freeze and the need to force-kill:
```urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:392: void __cdecl ecs::TransportNetworkSystem::EntityAdded(class ecs::Engine *,const class ecs::Entity &): Assertion `edge.conns[0] != edge.conns[1]' failed.```

**Comment by Gordon-Dry** [comment]
I just see there already is a dump file that occured during the loading process (time of crash was 15:36, there is a dump of 15:30) - and this dump file is 0 bytes! Weird....
[crash_dump.zip](https://github.com/lolluslollus/lollo_freestyle_train_station_1/files/10958700/crash_dump.zip)

see https://steamcommunity.com/groups/transportfever2_mac_vulkan/discussions/7/3788129296185615262/

**Comment by Gordon-Dry** [comment]
Did you report your discovery to UG? This is a real bummer and needs to be fixed asap.
Well, other stuff as well. 
Deadlines ...

**Comment by lolluslollus** [comment]
Sure, it's here: https://steamcommunity.com/groups/transportfever2_mac_vulkan/discussions/7/3781372149098039472/
No response from UG...

**Comment by Gordon-Dry** [comment]
With [latest repo from today](https://github.com/lolluslollus/lollo_freestyle_train_station_1/commit/da8fc53808d3db56c256b0ea05fe9e42d2bf3929) I dared to build a new station - after saving without pausing - and while not having the game  paused while placing the markers.
Success for the first platform. A red pin was placed in the middle of the track, though.
Then I paused the game like a bad boy and proceeded with the next platform. Another red pin.

Are those pins because of 
`local _isExtendedLogActive = true`
or is it the repo?

Or in other words:
Can I get rid off the markers later or do I have to bulldoze and rebuild the station?

**Comment by lolluslollus** [comment]
Yes, the pins come up with the extended log. No worries. As soon as you disable it, restart the game and make any dummy change to your station, they disappear.

**Comment by lolluslollus** [comment]
Question: did you load this game, which appears to work, from the same save as the one that crashed on start?

**Comment by Gordon-Dry** [comment]
Yes.

I must admit that I still assume it could have to do with the megalomaniac 1:5 map size and the fact that it happens near to the edges where the pointer unprecision is highest.

The last successfull station was not built near to the map edge but about 1:3 away from the map center.

**Comment by lolluslollus** [comment]
So this tima you did not get the dump while loading, even though it was the same savegame?
The error with saving while paused persists with 35300 by the way.
