### ISSUE TITLE
Feature Request: break track fence near crossings

### ISSUE THREAD

**Issue by Gordon-Dry** [lolluslollus/lollo_freestyle_train_station_1#12]
If I place the marker before the last node next to the railroad crossing, the fence ends at the middle of the road instead at the node:
![Screen-2023-03-03_13-59-16](https://user-images.githubusercontent.com/29145213/222726448-bfbe3a15-dc38-4b6a-b578-a39c7614d6bd.jpg)

![Screen-2023-03-03_13-59-32](https://user-images.githubusercontent.com/29145213/222726482-642a12b2-76f0-4744-bfb9-6381495aacc0.jpg)

**Comment by Gordon-Dry** [comment]
It also happens when I place the 2nd marker several node steps away of the last node - to the right on that screenshot.

**Comment by lolluslollus** [comment]
It should work by now,
