### ISSUE TITLE
Bulldozing track fence - the wrong piece is highlighted in yellow

### ISSUE THREAD

**Issue by Gordon-Dry** [lolluslollus/lollo_freestyle_train_station_1#13]
![Screen-2023-03-03_14-01-20](https://user-images.githubusercontent.com/29145213/222726889-e52d46d9-9700-4281-a49d-bd3310047ddb.jpg)

**Comment by Gordon-Dry** [comment]
That short piece belongs to the actual fence, though.

**Comment by lolluslollus** [comment]
I am aware of this and there is nothing I can do, ask UG.
