### ISSUE TITLE
v1.114: Placing track crossing module made game crash

### ISSUE THREAD

**Issue by Gordon-Dry** [lolluslollus/lollo_freestyle_train_station_1#15]
Brand new station with 3 platforms, just created and one exit ramp and a small exit building added, then added the track crossing module.
The game froze for a minute, then crashed.

End of log:
```
_getNodeBetween starting, shift0To1 =	0.50002668737964	length =	200.00022888184
pos0, pos1 =
{
  x = 369.06781005859,
  y = -20947.314453125,
  z = 125.02403259277,
}
{
  x = 187.43914794922,
  y = -21031.046875,
  z = 125.02403259277,
}
tan0, tan1 =
{
  x = -181.62867736816,
  y = -83.731925964355,
  z = 0,
}
{
  x = -181.62867736816,
  y = -83.731925964355,
  z = 0,
}
lollo_freestyle_train_station WARNING: could not find platformnode1Id in station construction; nTerminal =
1
lollo_freestyle_train_station WARNING: could not find tracknode1Id in station construction; nTerminal =
1
lollo_freestyle_train_station WARNING: could not find platformnode1Id in station construction; nTerminal =
1
lollo_freestyle_train_station WARNING: could not find tracknode1Id in station construction; nTerminal =
1
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/A9F18CB9FBA33F747B71F05AEC5E4C3A/totally_transparent_albedo.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/A9F18CB9FBA33F747B71F05AEC5E4C3A/totally_transparent_metal_gloss_ao.compressed.mm.dds not in file cache!
Pay extra for construction: 73, carrier: 1, constr: 1
Pay extra for construction: 73, carrier: 1, constr: 1
Pay extra for construction: 73, carrier: 1, constr: 1
Pay extra for construction: 73, carrier: 1, constr: 1
_getNodeBetween starting, shift0To1 =	0.50002668737964	length =	200.00022888184
pos0, pos1 =
{
  x = 366.97451782227,
  y = -20942.7734375,
  z = 125.02403259277,
}
{
  x = 185.34585571289,
  y = -21026.505859375,
  z = 125.02403259277,
}
tan0, tan1 =
{
  x = -181.62867736816,
  y = -83.731925964355,
  z = 0,
}
{
  x = -181.62867736816,
  y = -83.731925964355,
  z = 0,
}
lollo_freestyle_train_station WARNING: could not find platformnode1Id in station construction; nTerminal =
1
lollo_freestyle_train_station WARNING: could not find tracknode1Id in station construction; nTerminal =
1
lollo_freestyle_train_station WARNING: could not find platformnode1Id in station construction; nTerminal =
2
lollo_freestyle_train_station WARNING: could not find tracknode1Id in station construction; nTerminal =
2
lollo_freestyle_train_station WARNING: could not find platformnode1Id in station construction; nTerminal =
1
lollo_freestyle_train_station WARNING: could not find tracknode1Id in station construction; nTerminal =
1
lollo_freestyle_train_station WARNING: could not find platformnode1Id in station construction; nTerminal =
2
lollo_freestyle_train_station WARNING: could not find tracknode1Id in station construction; nTerminal =
2
Pay extra for construction: 16, carrier: 1, constr: 1
Pay extra for construction: 73, carrier: 1, constr: 1
Pay extra for construction: 73, carrier: 1, constr: 1
Pay extra for construction: 73, carrier: 1, constr: 1
Refund extra for construction: -55, carrier: 1, constr: 5
Pay extra for construction: 73, carrier: 1, constr: 1
Pay extra for construction: 73, carrier: 1, constr: 1
_getNodeBetween starting, shift0To1 =	0.50002515313131	length =	200.00022888184
pos0, pos1 =
{
  x = 356.50802612305,
  y = -20920.0703125,
  z = 125.02403259277,
}
{
  x = 174.87934875488,
  y = -21003.802734375,
  z = 125.02403259277,
}
tan0, tan1 =
{
  x = -181.62867736816,
  y = -83.731925964355,
  z = 0,
}
{
  x = -181.62867736816,
  y = -83.731925964355,
  z = 0,
}
lollo_freestyle_train_station WARNING: could not find platformnode1Id in station construction; nTerminal =
1
lollo_freestyle_train_station WARNING: could not find tracknode1Id in station construction; nTerminal =
1
lollo_freestyle_train_station WARNING: could not find platformnode1Id in station construction; nTerminal =
2
lollo_freestyle_train_station WARNING: could not find tracknode1Id in station construction; nTerminal =
2
lollo_freestyle_train_station WARNING: could not find platformnode2Id in station construction; nTerminal =
3
lollo_freestyle_train_station WARNING: WARNING: could not find tracknode2Id in station construction; nTerminal =
3
lollo_freestyle_train_station WARNING: could not find platformnode1Id in station construction; nTerminal =
1
lollo_freestyle_train_station WARNING: could not find tracknode1Id in station construction; nTerminal =
1
lollo_freestyle_train_station WARNING: could not find platformnode1Id in station construction; nTerminal =
2
lollo_freestyle_train_station WARNING: could not find tracknode1Id in station construction; nTerminal =
2
lollo_freestyle_train_station WARNING: could not find platformnode2Id in station construction; nTerminal =
3
lollo_freestyle_train_station WARNING: WARNING: could not find tracknode2Id in station construction; nTerminal =
3
Refund extra for construction: -13, carrier: 1, constr: 5
Pay extra for construction: 16, carrier: 1, constr: 1
Pay extra for construction: 14, carrier: 1, constr: 1
Pay extra for construction: 16, carrier: 1, constr: 1
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/A9F18CB9FBA33F747B71F05AEC5E4C3A/old_roof_tiles_albedo.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/A9F18CB9FBA33F747B71F05AEC5E4C3A/old_roof_tiles_normal.compressed.mm.rg8.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/7B8D22109DDB4B703192D966A1DD2686/big_04.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/7B8D22109DDB4B703192D966A1DD2686/big_05.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/A9F18CB9FBA33F747B71F05AEC5E4C3A/old_roof_tiles_metal_gloss_ao.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/B7BADDCFBE8B6DF53491371CA697EA38/Vsigbake3_hoch.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/DE7E18F3023041836D86395F6D672C8D/ETH_transparent.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/res/textures/unknown_texture.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/63FB4512C30B73EF314EF8847D65EFF1/power_pole_metal_gloss_ao.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/63FB4512C30B73EF314EF8847D65EFF1/power_pole_dark_albedo.compressed.mm.dds not in file cache!
::C:/Users/Admin/AppData/Roaming/Transport Fever 2/texture_cache/63FB4512C30B73EF314EF8847D65EFF1/power_pole_normal.compressed.mm.rg8.dds not in file cache!
urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:106: bool __cdecl `anonymous-namespace'::IsValidTransition(const struct transport::Edge &,const struct transport::Edge &,struct transport::NodeId): Assertion `person0 == person1' failed.
Attempting to write crash save to "crash_Region Goslar 04f_2023-03-05_19-12-14"
available disk space: 5789 MB
[2023-03-05 19:12:14] Saving to file C:/Users/Admin/AppData/Roaming/Transport Fever 2/save/crash_Region Goslar 04f_2023-03-05_19-12-14.sav
Saving...: 12822.9 ms
creating post-mortem savegame failed
Additional info extracted from the previous state:
 Additional info for entity 137693: 
 revision: 91 / 87 / 0
  components: 
   struct ecs::component::Name
   struct ecs::component::PlayerOwned
   struct ecs::component::BoundingVolume
   struct ecs::component::ModelInstanceList
   struct ecs::component::LotList
   struct ecs::component::TransportNetwork
   struct ecs::component::Construction
   struct ecs::component::BuildCost
   struct ecs::component::MaintenanceCost
   struct ecs::component::AudioEmitter
   struct ecs::component::TerrainAlignmentList
```
Log and dump:
[crash_dump.zip](https://github.com/lolluslollus/lollo_freestyle_train_station_1/files/10892583/crash_dump.zip)

**Comment by Gordon-Dry** [comment]
2nd try, this time only platforms done, no additional modules, first module is the track crossing, freeze, crash.
Weird thing is that there are 6 crash dumps in the folder, some of them already occured while I was loading the savegame ...
That did not happen the previous session.
It seems that just laying the platform tracks and normal tracks to prepare the station already was borked somehow.

[crash_dump.zip](https://github.com/lolluslollus/lollo_freestyle_train_station_1/files/10892747/crash_dump.zip)

**Comment by lolluslollus** [comment]
Try again on a map without other mods. I see you have 943 mods installed, including some dodgy ones (there is something dynamically altering the cost of tracks for example).
It appears the problem happened when trying to connect the station to its neighbouring tracks: the station could not find its own nodes and tracks!!! How long was your station? What tracks did you use?
If the problem happens again, describe in detail what you did. The game, as usual, fails to give useful information.

**Comment by Gordon-Dry** [comment]
Side note:
Since I use v1.114 every new platform created makes the tracks connecting to that platform - and sometimes also neighboring platforms - disconnected (red dots).
This never happened before since back in the days of really early versions of your mod.

I guess this is somehow related to the new issue.

**Comment by Gordon-Dry** [comment]
The station was only 200m long, 3 platforms.
I used the same tracks than always the last days and weeks, NEP² wooden sleepers 40 kph.

**Comment by Gordon-Dry** [comment]
On another station this did not happen.

Ideas by intuition:
- map is too big (megalomaniac)
- it's still the parallel-to-the-map-edge bug that was introduced with the first Tpf2 beta in January '23

**Comment by lolluslollus** [comment]
I cannot repro this unless you try without those other mods.
However, here is a new branch that makes pedestrian edges less fussy, and it contains some changes that might prevent your crash: https://github.com/lolluslollus/lollo_freestyle_train_station_1/tree/add-open-stairs-and-bridges-with-no-auto-links
Give it a try.

**Comment by lolluslollus** [comment]
This seems to be the trouble: urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:106: bool __cdecl `anonymous-namespace'::IsValidTransition(const struct transport::Edge &,const struct transport::Edge &,struct transport::NodeId): Assertion `person0 == person1' failed.
Please press AltGr + L and post a screenshot of your station.

**Comment by Gordon-Dry** [comment]
Actually I'm loading the game with latest main repo, dated on this commit https://github.com/lolluslollus/lollo_freestyle_train_station_1/commit/6fd010183d33c8cbaf4d09d7a8ad1d6de1965f55
and try to reproduce the crash as the station still exists, but without track crossings.
If it crashes, I try again with https://github.com/lolluslollus/lollo_freestyle_train_station_1/tree/add-open-stairs-and-bridges-with-no-auto-links and see what happens.

Or do I have to build a brand new station for that experiment? If yes, that is a problem as the issue did not always occur. Other stations did not have it.

**Comment by Gordon-Dry** [comment]
Oh, well, I just see there is only a small difference between main and https://github.com/lolluslollus/lollo_freestyle_train_station_1/tree/add-open-stairs-and-bridges-with-no-auto-links - a few lines of comments in res\construction\station\rail\lollo_freestyle_train_station\openLifts\openLift_NoAutoLink.module
So it does not matter and the crash still occurs.

**Comment by Gordon-Dry** [comment]
Parallel to the map edge: **nope**

Screenshots:

The cursor is at where I want to place the track crossing, **it's the middle node of the whole station** btw:
![Screen-2023-03-07_15-18-47](https://user-images.githubusercontent.com/29145213/223449087-bac5fdee-a254-4e0f-b719-9c2d1bff81b9.jpg)

The 10x10m ramp is not connected to the road when the 10x15 building is nearby:
![Screen-2023-03-07_15-21-10](https://user-images.githubusercontent.com/29145213/223449605-5ed9f3bc-d4c9-492f-bc87-c0d0df0ab086.jpg)

After removing the 10x15 building the ramp is connected to the road:
![Screen-2023-03-07_15-22-56](https://user-images.githubusercontent.com/29145213/223450177-95ffbe90-959e-4e57-b85c-b946dac47561.jpg)

The whole station again:
![Screen-2023-03-07_15-24-24](https://user-images.githubusercontent.com/29145213/223450623-0fe9a019-9e54-40b8-b039-3ab541ce0a7e.jpg)

I tried it again, it crashed again.

Perhaps the already built signals are the culprit? Usually it works like this as I - of course - placed the signals after the station was finished.
This time only that one line was written to the end of the log:
```urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:106: bool __cdecl `anonymous-namespace'::IsValidTransition(const struct transport::Edge &,const struct transport::Edge &,struct transport::NodeId): Assertion `person0 == person1' failed.```

**Comment by Gordon-Dry** [comment]
> At least try without other mods.

Which is not possible as the crash does not always happen as I already said.

**Comment by Gordon-Dry** [comment]
I will try to reproduce with two different scenarios:

1. same map, same station, but not the middle node (usually I never use the middle node as in most cases I don't build symatrical like on that scenario seen on the screenshots)
2. small map without mods, focusing on the middle node

**Comment by Gordon-Dry** [comment]
As I'm trying to reproduce without other mods on a tiny map I must admit that it's not easy to get a station with an odd number of nodes so the middle node is exactly where the track crossing could be set.
I will just add two more mods to make life easier for me:
https://steamcommunity.com/sharedfiles/filedetails/?id=2298331429
https://steamcommunity.com/sharedfiles/filedetails/?id=1965202795

**Comment by Gordon-Dry** [comment]
After a break of 2 hours I tried to reproduce and got a crash with a popup message, no need to force kill, just click "OK":
`Exception type: Fatal error`

But: the crash already happened as I wanted to create the first platform.

End of log from just after saving before trying:
```
Saving...: 391.313 ms
Additional info extracted from the previous state:
GC Called
Destroying failback ui done
Uncaught exception while in class UI::CSelector
Exception type: Fatal error

Details:

Assertion Failure: Assertion `!node.ports.empty()' failed.

Minidump: C:/Users/Admin/AppData/Roaming/Transport Fever 2/crash_dump/3e9de9e2-a8d0-4bbe-b719-28dd6427f9e4.dmp

In file: urban_games/train_fever/src/Lib/renderer/TransportNetworkRenderer.cpp:274

In function: void __cdecl TransportNetworkRenderer::Add(class ecs::Entity,const struct ecs::component::TransportNetwork &)


__CRASHDB_CRASH__ struct AssertException: urban_games/train_fever/src/Lib/renderer/TransportNetworkRenderer.cpp:274: void __cdecl TransportNetworkRenderer::Add(class ecs::Entity,const struct ecs::component::TransportNetwork &): Assertion `!node.ports.empty()' failed.
Exception type: Fatal error

Details:

Assertion Failure: Assertion `!node.ports.empty()' failed.

Minidump: C:/Users/Admin/AppData/Roaming/Transport Fever 2/crash_dump/3e9de9e2-a8d0-4bbe-b719-28dd6427f9e4.dmp

In file: urban_games/train_fever/src/Lib/renderer/TransportNetworkRenderer.cpp:274

In function: void __cdecl TransportNetworkRenderer::Add(class ecs::Entity,const struct ecs::component::TransportNetwork &)



Goodbye.



========================================
Shutdown at Tue Mar  7 18:01:48 2023
========================================
```

Log, dump and save from just before trying (3 dumps in a row at the same time):
[crash_dump and save.zip](https://github.com/lolluslollus/lollo_freestyle_train_station_1/files/10911998/crash_dump.and.save.zip)

**Comment by Gordon-Dry** [comment]
I disabled all mods but those 3 - but the CommonAPI .dll is still in there. I try again without it.

**Comment by Gordon-Dry** [comment]
Same issue, now I delete the shader and texture cache and try it again.

**Comment by Gordon-Dry** [comment]
This is how I placed the markers:
![Screen-2023-03-07_18-14-50](https://user-images.githubusercontent.com/29145213/223498035-5868e54c-02ed-4ecd-935b-5dcc05abdd15.jpg)
- The blue marker is at the end of the platform
- The green marker is 10 steps away from the blue marker's position, which is 8 steps left of the node

The same on the other side, but mirrored. As soon as I place the last marker, crash.

**Comment by Gordon-Dry** [comment]
Now I load the save without the other two mods and try again.
Same issue.

**Comment by Gordon-Dry** [comment]
Trying again with latest main repo.
Also crashes.

**Comment by Gordon-Dry** [comment]
Brand new tiny map, this time I could create a 3-platform station.

The central node is slightly off the position where track crossings are to be set:
![Screen-2023-03-07_18-54-07](https://user-images.githubusercontent.com/29145213/223507844-506aa080-a388-4b23-ad90-dadc0a3ca5c7.jpg)

I'm not sure but my intuition tells me that I need the central node exactly where the blue rectangles for placing track crossings are to reproduce the issue.

I will test this repo with my full savegame now.

**Comment by lolluslollus** [comment]
Thanks mate, I may know why it happens now: the track crossing node has, coincidentally, the same position as a track node. The game does not like it, because it is stupid, and it complains. Being really stupid, it crashes instead of mumbling politely. I am going to check this.

**Comment by lolluslollus** [comment]
OK try the main branch, I shifted the track crossing nodes away from the centre of the track.

**Comment by Gordon-Dry** [comment]
If you can do that, can you also check if the track crossing nodes are offset from one track to the neighboring parallel track?
This happens a lot with curved stations and makes them misaligned, so I don't use them then (I use assets instead).

I will test in a couple of minutes.

**Comment by Gordon-Dry** [comment]
Just to mention, with the first test save game that other issue still occurs:
Exception type: Fatal error

But okay, ... now I have to test the big map with that problem station, needs some time to load.

**Comment by lolluslollus** [comment]
Curves cannot be made to match coz every platform is split in arches, which are 10 m long. If I make them match, some arches will be shorter or longer. That is doable, but every platform should know where the other platforms are, which is impractical in a completely free layout.
I don't know about the other error, it could be anything. If you can repro it on a map without those other mods, you could send me the savegame. You can also turn on the extended log in logger.lua and produce a richer stdout.

**Comment by Gordon-Dry** [comment]
The main issue is fixed.

About the other issue: I will do that tomorrow. I wanna proceed in my gameplay now!

**Comment by lolluslollus** [comment]
I have a little surprise: for the same reason, flush exits can cause crashes, so I gelded them. You can still place your stairs at the end of a platform, but you must use a flat exit instead of flush. Sorry about that.
