### ISSUE TITLE
either Assertion `edge.conns[0] != edge.conns[1]' failed or Assertion `!node.ports.empty()' failed

### ISSUE THREAD

**Issue by Gordon-Dry** [lolluslollus/lollo_freestyle_train_station_1#20]
When building a station, at the end of the station track which is 10m longer than the station platform (on each end), I add additional 10m of track and then add the track marker to before the node of the first 10m segment, sparing the additional 10m segment for later use (signal placement on a straight piece), the game freezes and crashes with a popup message and:
```
urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:392: void __cdecl ecs::TransportNetworkSystem::EntityAdded(class ecs::Engine *,const class ecs::Entity &): Assertion `edge.conns[0] != edge.conns[1]' failed.
urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:392: void __cdecl ecs::TransportNetworkSystem::EntityAdded(class ecs::Engine *,const class ecs::Entity &): Assertion `edge.conns[0] != edge.conns[1]' failed.
Attempting to write crash save to "crash_Region Wittlich 03n_2023-04-14_16-38-35"
available disk space: 13336 MB
[2023-04-14 16:38:35] Saving to file C:/Users/Admin/AppData/Roaming/Transport Fever 2/save/crash_Region Wittlich 03n_2023-04-14_16-38-35.sav
Thread did not respond to ping. Possible hang detected!
Thread did not respond to ping. Possible hang detected!
Thread did not respond to ping. Possible hang detected!
Thread did not respond to ping. Possible hang detected!
Saving...: 9341.48 ms
Additional info extracted from the previous state:
 Additional info for entity 103503: 
 revision: 27 / 36 / 0
  components: 
   struct ecs::component::BuildCost
   struct ecs::component::MaintenanceCost
   struct ecs::component::AudioEmitter
   struct ecs::component::BoundingVolume
   struct ecs::component::ModelInstanceList
   struct ecs::component::TransportNetwork

nil

GC Called
Destroying failback ui done
Thread did not respond to ping. Possible hang detected!
Thread did not respond to ping. Possible hang detected!
Thread did not respond to ping. Possible hang detected!
Uncaught exception while in class UI::CSelector
Thread did not respond to ping. Possible hang detected!
End of redirect Buffer to StdOutBuffer
Restoring as we are still responsible for stdout
End of redirect Buffer to StdOutBuffer: done
Exception type: Fatal error

Details:

Assertion Failure: Assertion `edge.conns[0] != edge.conns[1]' failed.

Minidump: C:/Users/Admin/AppData/Roaming/Transport Fever 2/crash_dump/d5fce3b0-0e9b-400a-b868-ca9f1720b0dc.dmp

Entity: 103503

Notified Entity: 103503

UI Component Hierarchy: 
 type: class UI::CGameUI, id = "", name = "CGameUI", styleClasses = {"top-gamebar-visible"}
 type: class UI::CMenuUI, id = "", name = "MenuUI", styleClasses = {}
 type: class UI::CComponent, id = "", name = "wrap", styleClasses = {"platform-desktop", "ui-classic", "input-mouse", "gamepad-type-xbox"}


In file: urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:392

In function: void __cdecl ecs::TransportNetworkSystem::EntityAdded(class ecs::Engine *,const class ecs::Entity &)


__CRASHDB_CRASH__ struct AssertException: urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:392: void __cdecl ecs::TransportNetworkSystem::EntityAdded(class ecs::Engine *,const class ecs::Entity &): Assertion `edge.conns[0] != edge.conns[1]' failed.
Exception type: Fatal error

Details:

Assertion Failure: Assertion `edge.conns[0] != edge.conns[1]' failed.

Minidump: C:/Users/Admin/AppData/Roaming/Transport Fever 2/crash_dump/d5fce3b0-0e9b-400a-b868-ca9f1720b0dc.dmp

Entity: 103503

Notified Entity: 103503

UI Component Hierarchy: 
 type: class UI::CGameUI, id = "", name = "CGameUI", styleClasses = {"top-gamebar-visible"}
 type: class UI::CMenuUI, id = "", name = "MenuUI", styleClasses = {}
 type: class UI::CComponent, id = "", name = "wrap", styleClasses = {"platform-desktop", "ui-classic", "input-mouse", "gamepad-type-xbox"}


In file: urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:392

In function: void __cdecl ecs::TransportNetworkSystem::EntityAdded(class ecs::Engine *,const class ecs::Entity &)



Goodbye.



========================================
Shutdown at Fri Apr 14 16:42:24 2023
========================================
```
[crash_dump.zip](https://github.com/lolluslollus/lollo_freestyle_train_station_1/files/11234026/crash_dump.zip)

**Comment by Gordon-Dry** [comment]
This is the state of just before adding the markers, from top to bottom platforms 1 to 5.
![Screen-2023-04-14_17-14-44](https://user-images.githubusercontent.com/29145213/232084578-9be36f25-0181-4fea-97f0-fc5950f7e8ff.jpg)
The first two platforms did well, the 3rd platform also seemed to get done as the mod claimed that it was just added, but afterwards it started to freeze and then it crashed.

**Comment by Gordon-Dry** [comment]
Sometimes it's 
```Assertion Failure: Assertion `edge.conns[0] != edge.conns[1]' failed.```
Sometimes it's
```Assertion Failure: Assertion `!node.ports.empty()' failed.```

It always happens when I try to
- add a platform + track to an existing station
- the station is not straight, but curved (even when only slightly)
- the station is asymetric, so the new platform is shorter and/or offset relative to the previous platform

This is the screenshot of the last save just before trying to add a 2nd platform to the station:
![Region Heringen 01o4](https://user-images.githubusercontent.com/29145213/233791566-43fe7413-a5bd-4d33-86f9-c81b31575574.jpg)
The 2nd platform should be the shorter terminus  next to the road, which ends at the station building

**Comment by Gordon-Dry** [comment]
I just tried it again, but with another order in which I placed the markers - and this time it did not crash with a popup message, it just froze and only one line was written to stdout.txt:
```urban_games/train_fever/src/Game/ecs/TransportNetworkSystem.cpp:392: void __cdecl ecs::TransportNetworkSystem::EntityAdded(class ecs::Engine *,const class ecs::Entity &): Assertion `edge.conns[0] != edge.conns[1]' failed.```

**Comment by Gordon-Dry** [comment]
These issues seem never to occur when I always build station tracks with the exact same length as the platforms without adding 10m of track on each end and placing the green markers there.

This means a station with more place for locomotives - so that all waggons are in reach of the platforms - is not possible without crashing the game, unfortunately.

**Comment by lolluslollus** [comment]
This is weird, can you post a savegame without other mods on wetransfer or swisstransfer?
By the way, Github does not notify me when you write into it.

**Comment by Gordon-Dry** [comment]
It seems that in most cases the issue is triggered if the mod
https://steamcommunity.com/workshop/filedetails/?id=2368852720
is enabled, but only if the mod's status bar icon is set to "enabled".

So the issue is gone if the mod is installed, but not enabled ingame.

As that mod gave no benefit because the mods "bridge devs" do not support its functionality I just removed it.

I'm still careful in planning freestyle train stations but I will start trying the same stuff again that was a problem earlier.

**Comment by lolluslollus** [comment]
I don't use that mod and I think we got past this in a separate discussion. I rarely check github, use steam for faster communication.
