### ISSUE TITLE
Cannot build a station anymore with latest betas 35705+

### ISSUE THREAD

**Issue by Gordon-Dry** [lolluslollus/lollo_freestyle_train_station_1#22]
see https://steamcommunity.com/workshop/filedetails/discussion/2363493916/3108016147991274001/?ctp=6#c3803902423391640872

With the latest betas (build 35705+) I cannot build a station anymore, after a longer time than I'm used to for a new station the platform track and the railroad track are not converted to a station, but they just disappear.
The "BuildInProgress" UI popup just stays there, I can manually close it.
There is a huge block in the stdout.txt written by this mod.
No crash, even no crash dump written.

Starts at line 11030 and goes up to 27152:
[https://www.dropbox.com/scl/fi/85zbod1r6wjthxca53zhh/stdout-2023100701.7z?rlkey=gxzt5ahi7irc8d03h5akbbt3s&dl=1](https://steamcommunity.com/linkfilter/?url=https://www.dropbox.com/scl/fi/85zbod1r6wjthxca53zhh/stdout-2023100701.7z?rlkey=gxzt5ahi7irc8d03h5akbbt3s&dl=1)

**Comment by lolluslollus** [comment]
The master branch should finally fix your problem, check it out.
