### ISSUE TITLE
All new stations have no build options anymore with "Early Start" mod

### ISSUE THREAD

**Issue by Gordon-Dry** [lolluslollus/lollo_freestyle_train_station_1#8]
Even after building a brand new station it looks like this:
![Screen-2023-02-20_23-20-15](https://user-images.githubusercontent.com/29145213/220206633-0323ddf5-c2cd-4fd6-8d34-c15031e86c09.jpg)
Every tab is empty.

This was with the latest repo [fill glitchy gaps in walls, like I did with roofs](https://github.com/lolluslollus/lollo_freestyle_train_station_1/commit/b6bb882a82c2a25b8d09fd87be2a8f6099e39798) and also with the latest stable build from Steam workshop.

Within the last days I already have seen that on older stations and thought "okay, that's the price to pay for using beta versions", but now I always have that, even with new stations.
So I assume I already had that issue for days, but didn't recognize it soon enough ...

Is my savegame borked now?

**Comment by lolluslollus** [comment]
Strange. What happens if you remove a terminal and make it again? With the Steam version?

**Comment by Gordon-Dry** [comment]
Just that. Even removing a terminal on an existing station or building a brand new station; same result.

**Comment by Gordon-Dry** [comment]
Actually I try to start a brand new game, as I was unsatisfied by the map whatsoever.
For starting the save I use the latest stable version.
But the old savegame is still there for testing.

**Comment by Gordon-Dry** [comment]
It also happens with new started games, see https://steamcommunity.com/workshop/filedetails/discussion/2363493916/3772365358798118417/

**Comment by Gordon-Dry** [comment]
There is no error message in the stdout.txt, the only thing was the result of setting the markers and creating platforms successfully.

**Comment by Gordon-Dry** [comment]
Allright. Removing [Early Start](https://steamcommunity.com/sharedfiles/filedetails/?id=2617346426) fixed the issue.
It was not a problem in earlier versions of this mod.
I even tried to override it by changing line 77 in res\scripts\lollo_freestyle_train_station\constants.lua to
` era_a = { prefix = 'era_a_', startYear = 1700 },`

**Comment by Gordon-Dry** [comment]
At some point during the development phase of new fences and walls within the last 2-3 weeks the compatibility to Early Start was broken.
Before that point, during the development phase of axial exits etc. it still was compatible.

**Comment by Gordon-Dry** [comment]
see https://steamcommunity.com/workshop/filedetails/discussion/2363493916/3772365358798118417/#c3772365358800421703
It seems I fixed it. I need a last test run before I can confirm.
